version: '3.8'

services:
  api:
    image: node:20.11.1-alpine
    working_dir: /api
    command: >
      sh -c "yarn install
      && yarn migration:run
      && yarn prisma db pull
      && yarn prisma generate
      && yarn dev"
    ports:
      - 4000:4000
    volumes:
      - ./:/api
      - /api/node_modules
    environment:
      PORT: 4000
      NODE_ENV: development
      TZ: America/Sao_Paulo
      DATABASE_URL: mysql://root:senha_root_123@mysqldb:3306/wefit
      DB_HOST: mysqldb
      DB_USER: root
      DB_PORT: 3306
      DB_PASSWORD: senha_root_123
      DB_NAME: wefit
    depends_on:
      - mysqldb
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.6
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=senha_root_123
      - MYSQL_DATABASE=wefit
    ports:
      - 3306:3306
    volumes:
      - ./data/:/var/lib/mysql

networks:
  default:
    name: app-network
